sogrep: attempt to polish into a finished product
Adds:
- help text
- proper option parsing
- downloads the cache for the first time, if needed
- rename "recache" subcommand to a --refresh option and make it work at
  the same time as a grep; the name was ugly...
- properly bomb out when using nonexistent repos or too few options

diff --git a/bin/sogrep b/bin/sogrep
--- a/bin/sogrep
+++ b/bin/sogrep
@@ -5,6 +5,7 @@
 repos=('staging' 'testing' 'core' 'extra' 'community-staging' 'community-testing' 'community' 'gnome-unstable' 'kde-unstable')
 arches=('x86_64')
 
+source /usr/share/makepkg/util/util.sh
 
 recache() {
     local repo arch
@@ -22,8 +23,18 @@ search() {
     local repo=$1 arch lib=$2
 
     if [[ $repo != all ]]; then
+        if ! in_array "$repo" "${repos[@]}"; then
+            echo "${BASH_SOURCE[0]##*/}: unrecognized repo '$repo'"
+            echo "Try '${BASH_SOURCE[0]##*/} --help' for more information."
+            exit 1
+        fi
         local repos=("${repo}")
     fi
+
+    if [[ ! -d ${SOCACHE_DIR} ]]; then
+        recache
+    fi
+
     for arch in "${arches[@]}"; do
         for repo in "${repos[@]}"; do
             db=${SOCACHE_DIR}/${arch}/${repo}/
@@ -37,11 +48,45 @@ search() {
      done | sort -u
 }
 
-case $1 in
-    recache)
-        recache
-        ;;
-    *)
-        search "$@"
-        ;;
-esac
+usage() {
+    cat <<- _EOF_
+		Usage: ${BASH_SOURCE[0]##*/} [OPTIONS] REPO LIBNAME
+
+		Check the soname links database for pacman repositories containing
+		packages linked to a given shared library
+
+		If the links database does not exist, it will be downloaded first.
+
+		OPTIONS
+		    -r, --refresh   Refresh the links databases
+		    -h, --help      Show this help text
+_EOF_
+}
+
+if (( $# == 0 )); then
+    echo "error: No arguments passed."
+    echo "Try '${BASH_SOURCE[0]##*/} --help' for more information."
+    exit 1
+fi
+
+while (( $# )); do
+    case $1 in
+        -r|--refresh)
+            recache
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        *)
+            if (( $# < 2 )); then
+                echo "error: Not enough arguments passed."
+                echo "Try '${BASH_SOURCE[0]##*/} --help' for more information."
+                exit 1
+            fi
+            search "$@"
+            exit $?
+            ;;
+    esac
+    shift
+done
